# Generated by Django 2.1.3 on 2018-11-29 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beta_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('video', models.URLField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='areas.Area')),
            ],
        ),
    ]
