# Generated by Django 2.1.3 on 2018-11-29 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boulder_Wall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='areas.Area')),
            ],
        ),
        migrations.CreateModel(
            name='City_Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='areas/media/')),
            ],
        ),
        migrations.AddField(
            model_name='city_town',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='areas.State'),
        ),
        migrations.AddField(
            model_name='area',
            name='city_town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='areas.City_Town'),
        ),
    ]
