# Generated by Django 2.1.3 on 2018-12-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city_town',
            name='latitude',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city_town',
            name='longitude',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
