# Generated by Django 2.1.7 on 2019-03-25 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='areas/media/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
