# Generated by Django 2.1.7 on 2019-03-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_auto_20190325_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_town',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
