# Generated by Django 2.1.3 on 2018-12-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_auto_20181207_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='abbrv',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
