# Generated by Django 2.1.3 on 2018-12-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_state_abbrv'),
    ]

    operations = [
        migrations.AddField(
            model_name='city_town',
            name='timezone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
