# Generated by Django 2.1.7 on 2019-05-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_auto_20190503_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_town',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
