# Generated by Django 2.1.3 on 2018-12-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_city_town_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_town',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='city_town',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
