# Generated by Django 2.1.9 on 2019-06-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0006_auto_20190624_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_town',
            name='permit_required',
            field=models.BooleanField(default=False),
        ),
    ]
