# Generated by Django 2.0.6 on 2019-02-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0006_auto_20181220_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city_town',
            name='id',
        ),
        migrations.AlterField(
            model_name='city_town',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
