# Generated by Django 2.0.6 on 2019-02-13 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0002_remove_problem_location'),
        ('areas', '0007_auto_20190212_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='city_town',
        ),
        migrations.RemoveField(
            model_name='boulder_wall',
            name='area',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Boulder_Wall',
        ),
    ]
