# Generated by Django 2.1.9 on 2019-07-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0008_auto_20190624_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_town',
            name='camping',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='city_town',
            name='nearby_food',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='city_town',
            name='permit_required',
            field=models.NullBooleanField(),
        ),
    ]
