language: python
python:
  - '3.6'

services:
  - docker

before_install:
#  - sudo apt-get install python3-dev
  - docker build -t web:latest .
  - docker run -d --name climbbeta -e "PORT=8765" -p 8007:8765 web:latest
  - docker ps -a

install: skip