language: python
python:
  - '3.6'

services:
  - docker

install: pip install -r requirements.txt

script:
  - python manage.py test
  - docker build -t web:latest .
  - docker run -d --name climbbeta -e "PORT=8765" -p 8007:8765 web:latest
  - docker ps -a
  