language: python
python:
  - '3.6'

services:
  - docker

install: skip

stages:
  - test
  - build
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      script:
        - docker-compose up -d
        - docker exec climbbeta-web-container python manage.py test
        - docker-compose down
    - stage: build
      script:
        - docker build -t registry.heroku.com/develop-climbbeta/web .
    - stage: deploy
      script:
        - curl https://cli-assets.heroku.com/install.sh | sh
        - heroku login
        - heroku container:login
        - docker push registry.heroku.com/develop-climbbeta/web
        - heroku container:release -a develop-climbbeta web
