# Generated by Django 2.1.7 on 2019-03-05 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todays_Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('main', models.CharField(max_length=100)),
                ('temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('desc', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='areas.City_Town')),
            ],
        ),
        migrations.CreateModel(
            name='Weather_Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daytime', models.DateTimeField()),
                ('temp', models.FloatField()),
                ('desc', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='areas.City_Town')),
            ],
        ),
    ]
