# Generated by Django 2.0.6 on 2019-02-13 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0008_auto_20190213_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todays_Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('main', models.CharField(max_length=100)),
                ('temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('pressure', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('desc', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='areas.City_Town')),
            ],
        ),
        migrations.CreateModel(
            name='Weather_Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daytime', models.DateTimeField()),
                ('temp', models.FloatField()),
                ('desc', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='areas.City_Town')),
            ],
        ),
    ]
