# Generated by Django 2.0.6 on 2019-02-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todays_weather',
            name='humidity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todays_weather',
            name='date',
            field=models.IntegerField(),
        ),
    ]
