# Generated by Django 2.1.7 on 2019-03-17 19:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_name', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('grade', models.ManyToManyField(to='climbs.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_stars', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Sent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reflection', models.TextField()),
                ('sent_problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='climbs.Problem')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='stars',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='climbs.Rating'),
        ),
    ]
