# Generated by Django 2.0.6 on 2019-02-13 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='location',
        ),
    ]
