# Generated by Django 2.0.6 on 2019-02-12 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0006_auto_20181220_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('thumbnail', models.URLField()),
                ('embed', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='areas.City_Town')),
            ],
            options={
                'db_table': 'videos',
            },
        ),
    ]
