# Generated by Django 2.1.7 on 2019-04-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='created',
            field=models.CharField(max_length=255),
        ),
    ]
