# Generated by Django 2.1.7 on 2019-03-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='uri',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
