# Generated by Django 2.0.6 on 2019-02-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20190212_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='id',
        ),
        migrations.AlterField(
            model_name='videos',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
