# Generated by Django 2.0.6 on 2019-02-13 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20190212_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='areas.City_Town'),
        ),
    ]
