# Generated by Django 2.0.6 on 2019-02-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20190213_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
