# Generated by Django 2.0.6 on 2019-02-13 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20190213_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='city',
        ),
    ]
