# Generated by Django 2.0.6 on 2019-02-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_remove_videos_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name_plural': 'Videos'},
        ),
    ]
