# Generated by Django 2.1.7 on 2019-02-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_auto_20190213_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
